### ISSUE TITLE
中文翻譯【隱藏工具列】吧?

### ISSUE THREAD

**Issue by DKMonster** [Sheng-Bo/atom-cht-menu#1]
![hidden menu](https://cloud.githubusercontent.com/assets/5243632/8530838/13c01b78-2456-11e5-8898-5a4165535f04.jpg)

這是隱藏工具列?

**Comment by Sheng-Bo** [comment]
感謝提醒，剛剛補上。另外隱藏功能選單後，可以使用 Alt 鍵叫回選單呦 :)
