### ISSUE TITLE
Windows 10 Issue

### ISSUE THREAD

**Issue by yiming** [Sheng-Bo/atom-cht-menu#4]
1. Windows 10底下:
2. 1366_768的字型, 跟 1920_1080的字型 , 字型render方式不同, 
3. 1366中文字有hinting, 1920沒有hinting
4. 安裝完cht-menu完後, 關掉atom再重開後, settings視窗左側選單, 會回復為英文
   ![2015-12-23 4](https://cloud.githubusercontent.com/assets/333365/11971477/807112e2-a979-11e5-894a-1b08ae1c2f6b.png)
   ![2015-12-23 5](https://cloud.githubusercontent.com/assets/333365/11971478/8073ac32-a979-11e5-9003-f645a2ead106.png)
   ![2015-12-23 6](https://cloud.githubusercontent.com/assets/333365/11971479/8073e620-a979-11e5-94ed-77240b994aae.png)

**Comment by Sheng-Bo** [comment]
感謝您回報 issue。小弟目前進度為先將 Windows 下自動判別使用者是否有指定字型，有的話就用該字型，沒有就用微軟正黑體。我也有發現好幾處英文沒有改過去中文的地方，繼續研究中。
