### ISSUE TITLE
安装完之后就报错,atom版本1.11.1

### ISSUE THREAD

**Issue by timy-life** [Sheng-Bo/atom-cht-menu#6]
![image](https://cloud.githubusercontent.com/assets/13111713/19373994/f4bb9e46-91fa-11e6-9513-11d3932e0d54.png)

**Comment by Sheng-Bo** [comment]
不好意思，現在才看到回報。目前在 1.12.7 下測試無錯誤。從您提供的畫面上看來，是 Atom 沒有隨著 package 的要求抓 cson node module 下來。
